### ISSUE TITLE
Fix links to freecad domain in code and README (freecadweb.org -> freecad.org)

### ISSUE THREAD

**Issue by luzpaz** [EdgarJRobles/dodo#2]
* https://github.com/EdgarJRobles/dodo/blob/master/README.md#links

**Comment by EdgarJRobles** [comment]
The last commits & updates are on feat/translation++ branch
https://github.com/EdgarJRobles/dodo/tree/feat/translation%2B%2B

**Comment by hasecilu** [comment]
263e7bad65aa
